### ISSUE TITLE
Vote Button

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-module-consultations#10]
Because right now the voting platform is not decided, we have two options:
1. Select in the consultation configuration if Decidim record the votes or whether it will be an external platform. The vote configuration with external systems, will take place later, once the decision is made
2. The button take no action

@xabier  What you think is most appropriate at this time?

**Comment by xabier** [comment]
@andreslucena ?

**Comment by xabier** [comment]
We want the following to happen when the Vote button is pressed. 

1. When Decidim is used combined with a secure eVoting SaaS --> a 
2. When Decidim is used as-is:
    - Admins define a set of responses to the question: number of responses and content of responses
    - Users click the vote button and a pop-up displays the question and the responses followed (or preceeded) by a button to select that response.
    - Once voted the vote-button appears as "already voted"

**Comment by htmlboy** [comment]
Hi! I can add a new view with a modal prompt in the HTML prototype I'm preparing, no problem.

**Comment by jsperezg** [comment]
@htmlboy Where can I access to the html prototype?

**Comment by htmlboy** [comment]
@jsperezg https://github.com/decidim/design/pull/178
