### ISSUE TITLE
Icon for consultations sections

### ISSUE THREAD

**Issue by jsperezg** [decidim/decidim-module-consultations#22]
# This is a Feature Proposal

#### :tophat: Description
We need an icon for this engine.

**Comment by xabier** [comment]
@htmlboy can you provide one?

I have this in mind: 
![image](https://user-images.githubusercontent.com/537284/35044878-35b27b02-fb92-11e7-9c34-b8f44c972e82.png)

**Comment by jsperezg** [comment]
Could you please check the svg icon that you sent me? As soon as I added it to the project the rendering start failing with this error:

incompatible character encodings: UTF-8 and ASCII-8BIT

**Comment by jsperezg** [comment]
@htmlboy I forgot to mention you

**Comment by jsperezg** [comment]
I've tried replacing the checkmark by its html entity:

&#10003;

without any success. The error dissapears, but it draws nothing

**Comment by htmlboy** [comment]
@xabier I can take a look. I'm not sure this mockup looks distinctive enough, maybe something like a polling box? Would it be a "political problem"? Or maybe this is something for the UX team, since they are already reviewing the icon system?

@jsperezg I'm not sure Xabier's icon was production-ready… is the integration something temporary?

**Comment by xabier** [comment]
The problem is that a ballot-box icon is already in use for the voting component developed here https://github.com/podemos-info/decidim-module-votings

**Comment by htmlboy** [comment]
@xabier I see! But that polling icon doesn't follow the general style of the Decidim icons (the fact that we don't have a design guide for the icons is part of the problem, indeed). Shouldn't these icons be controlled by the UX team, then?

**Comment by xabier** [comment]
> Shouldn't these icons be controlled by the UX team, then?

Yes, they already did the job. Can't find the link from mobile.
