### ISSUE TITLE
Scope and origin in question's technical info

### ISSUE THREAD

**Issue by jsperezg** [decidim/decidim-module-consultations#23]
# This is a Feature Proposal

#### :tophat: Description

The mockup's regarding the question public views show a technical view page which contains, among others, the following attributes:

Ambito/Scope: In the example appears the value 'Iniciativa ciudadana'
Origen/Origin: In the example seems to be a link pointing to an initiative. The link text is the initiative title in the corresponding locale.

There is nothing similar in all decidim, in fact, for initiatives we left this feature out of the MVP (result of the initiative was supposed to be the same or quite similar thing).

For this reason we need a definition about how to implement this feature. As I see it, we have two possibilities:

* Complex solution: Create a component/input that filters between participatory spaces and allows users to select one. The complexity of this solution is high due to several factors:

  * Participatory processes always exist in decidim. Assemblies and initiatives don't. There is no security about the existence of all tables/models when the engine executes the query.

  * The criteria to select a participatory space should be provided by the engine that implements it in order to avoid coupling between components. This implies making changes in initiatives, assemblies, participatory processes engine and of course the core, creating an input component that can be reutilized accross the platform to create references between any element and a participatory space.

  * Another risk is that, considering the deadline for this project, relaying in a feature that must be included and deployed in the core first can delay the project.

* Basic solution: Create 2/3 attributes that will be filled by hand:
  * Ambito/Scope: Descripiton of the scope
  * Origin URL: Link to participatory space
  * Origin title: Title for the link. With support for multiple languages.

The drawback with this solutions are obvious:
  * Three inputs need to be filled instead of one.
  * Origin URL may contain parameters related to the user locale if the user do not take care to remove them when he paste it.
  * Title is an information already available in the system but needs to be copied & pasted, once per language. If it changes the information in the question would become outdated.

The advantages are obvious as well:
  * The first solution soposes more than 1 week of development. This can be implemented in hours.

We need to take a decission about this. Any idea that improves the both suggested above is wellcome.

**Comment by jsperezg** [comment]
@xabier @htmlboy What are your thoughts regarding this topic?

**Comment by josepjaume** [comment]
@jsperezg I agree on that adding a participatory space selector is costly. That said, we recently merged a PR that allow you to get the participatory spaces for an organization:

https://github.com/decidim/decidim/blob/master/decidim-participatory_processes/lib/decidim/participatory_processes/participatory_space.rb#L9..L11

This should make the issue a bit easier in conjunction with the `public` scope that all participatory spaces have.

IMO we should go with option 2 in order to be able to meet the deadline, but put this in a issue so it can be worked on afterwards.

**Comment by jsperezg** [comment]
Completelly agree @josepjaume
