### ISSUE TITLE
Add Question to Consultations

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-module-consultations#3]
As administrator, I want to add question to a consultation .Question requiered fields are:

- Title (required)
- Que se decide 
- Contexto
- Video
- Promoter group (required)
- Municipal area (required)
- Scope of participation (required)
- Associated hastag
- Decidim refence (BCN-PROP-2017-0711999)
- Start date (required)
- End date (required)

@xabier It is necessary to put an individual published field per question ?

**Comment by xabier** [comment]
> It is necessary to put an individual published field per question ?

YES

**Comment by ailopezglez** [comment]
We have agreed that the questions can be published individually
