### ISSUE TITLE
Reference in questions

### ISSUE THREAD

**Issue by jsperezg** [decidim/decidim-module-consultations#31]
# This is a Bug Report

#### :tophat: Description
The mockups show that questions have a reference. The problem with this is that current the HasReference concern only applies to features and a question, since have features itself, is a participatory space.

@xabier  @ailopezglez We should disscuss about how important is this feature for the MVP and, in case it's a must find a way to have references in participatory spaces.

**Comment by jsperezg** [comment]
@mrcasals already did it: 

https://github.com/decidim/decidim/issues/2527

**Comment by jsperezg** [comment]
@xabier In order to be ready to deploy this feature ASAP in the future I've added all the required code to the current base code: The reference field exists as well as all visual elements required to show it. As soon as it is implemented in core we will need to change just two files:

version.rb: in order to increase the version number
question.rb: Add the HasReference concern to the question model.

**Comment by xabier** [comment]
@jsperezg well done!

**Comment by jsperezg** [comment]
https://github.com/decidim/decidim/pull/2557

**Comment by jsperezg** [comment]
This feature is already implemented but won't be available until Decidim 0.10.

**Comment by xabier** [comment]
this is perfect! thanks! I close this issue
