### ISSUE TITLE
Banner omnipresent

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-module-consultations#39]
In order to highlight a global message to the platform, the intention is to develop an ominpresent banner, according to the attached design
The administrator must be able to fill in:

- Title
- Short description
- Link text
- Link Url

![captura de pantalla 2018-01-22 a las 13 10 05](https://user-images.githubusercontent.com/30348400/35220168-987f79ce-ff75-11e7-8c26-845d5a65566c.png)

**Comment by jsperezg** [comment]
Reviewed on Feb, 1st during the sprint meeting
