### ISSUE TITLE
I cannot update the Question in the Consultations

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-module-consultations#81]
_From @Xfolchf on March 19, 2018 10:31_

# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?
I have created a Question for testing the funcionality. First time it worked, but when updating information now appears the message: 
"The page you are looking for has not been found"

https://meta.decidim.barcelona/processes/bug-report/f/210/proposals/12315

#### :pushpin: Related issues
* #12345

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***: 0.9.x
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

_Copied from original issue: decidim/decidim#3030_

**Comment by jsperezg** [comment]
@mrcasals Both @xabier and me have tried to reproduce this issue unsuccessfully. 

We've tests for forms, commands and integration tests for the question update feature and all of them pass successfully.

**Comment by mrcasals** [comment]
@jsperezg I simply moved the issue from the other repo, if you can't reproduce it then close it 😄

**Comment by jsperezg** [comment]
cool @mrcasals
